I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script-a2-meetcompute_1.rpy", line 9, in script
    e "It's raining. Hard."
Exception: Sayer 'e' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script-a2-meetcompute_1.rpy", line 9, in script
    e "It's raining. Hard."
  File "C:\Users\19173\Dropbox\PC (2)\Desktop\renpy-7.4.11-sdk\renpy\ast.py", line 881, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\19173\Dropbox\PC (2)\Desktop\renpy-7.4.11-sdk\renpy\ast.py", line 774, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'e' is not defined.

Windows-10-10.0.19044 AMD64
Ren'Py 8.0.1.22070801
LOVExCOMPUTER 1.0
Sat Aug 13 20:52:06 2022
