I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script-a2-meetcompute-1.rpy", line 42, in script
    "Before you turn around, you know the source."
OSError: Couldn't find file 'audio/TI_FP_VCTK_line3.wav'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script-a2-meetcompute-1.rpy", line 42, in script
    "Before you turn around, you know the source."
  File "C:\Users\19173\Dropbox\PC (2)\Desktop\renpy-7.4.11-sdk\renpy\ast.py", line 921, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\Users\19173\Dropbox\PC (2)\Desktop\renpy-7.4.11-sdk\renpy\exports.py", line 1373, in say
    who(what, *args, **kwargs)
  File "C:\Users\19173\Dropbox\PC (2)\Desktop\renpy-7.4.11-sdk\renpy\character.py", line 1266, in __call__
    self.do_display(who, what, cb_args=self.cb_args, dtt=dtt, **display_args)
  File "C:\Users\19173\Dropbox\PC (2)\Desktop\renpy-7.4.11-sdk\renpy\character.py", line 927, in do_display
    display_say(who,
  File "C:\Users\19173\Dropbox\PC (2)\Desktop\renpy-7.4.11-sdk\renpy\character.py", line 666, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "C:\Users\19173\Dropbox\PC (2)\Desktop\renpy-7.4.11-sdk\renpy\ui.py", line 299, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\Users\19173\Dropbox\PC (2)\Desktop\renpy-7.4.11-sdk\renpy\display\core.py", line 3377, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, **kwargs) # type: ignore
  File "C:\Users\19173\Dropbox\PC (2)\Desktop\renpy-7.4.11-sdk\renpy\display\core.py", line 4097, in interact_core
    renpy.audio.audio.periodic()
  File "C:\Users\19173\Dropbox\PC (2)\Desktop\renpy-7.4.11-sdk\renpy\audio\audio.py", line 1166, in periodic
    raise_(exc[0], exc[1], exc[2])
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python3.9/site-packages/future/utils/__init__.py", line 441, in raise_
  File "C:\Users\19173\Dropbox\PC (2)\Desktop\renpy-7.4.11-sdk\renpy\audio\audio.py", line 1144, in periodic_thread_main
    periodic_pass()
  File "C:\Users\19173\Dropbox\PC (2)\Desktop\renpy-7.4.11-sdk\renpy\audio\audio.py", line 1086, in periodic_pass
    c.periodic()
  File "C:\Users\19173\Dropbox\PC (2)\Desktop\renpy-7.4.11-sdk\renpy\audio\audio.py", line 517, in periodic
    topf = load(filename)
  File "C:\Users\19173\Dropbox\PC (2)\Desktop\renpy-7.4.11-sdk\renpy\audio\audio.py", line 70, in load
    rv = renpy.loader.load(fn)
  File "C:\Users\19173\Dropbox\PC (2)\Desktop\renpy-7.4.11-sdk\renpy\loader.py", line 820, in load
    raise IOError("Couldn't find file '%s'." % name)
OSError: Couldn't find file 'audio/TI_FP_VCTK_line3.wav'.

Windows-10-10.0.19044 AMD64
Ren'Py 8.0.1.22070801
LOVExCOMPUTER 1.0
Tue Aug 16 22:24:27 2022
